export const FETCH_INVOICES_DATA_REQUEST = 'FETCH_INVOICES_DATA_REQUEST';
export const FETCH_INVOICES_DATA_SUCCESS = 'FETCH_INVOICES_DATA_SUCCESS';
export const FETCH_INVOICES_DATA_FAILURE = 'FETCH_INVOICES_DATA_FAILURE';

export const FILTER_INVOICES = 'FILTER_INVOICES';
